packages:
  - apps/*
  - packages/*

catalog:
  "@cloudflare/vite-plugin": ^1.29.1
  "@orpc/client": ^1.13.8
  "@polar-sh/better-auth": ^1.8.3
  "@tailwindcss/vite": ^4.2.2
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  astro: ^6.0.6
  better-auth: ^1.5.5
  clsx: ^2.1.1
  nucleo-ui-outline-18: ^1.3.2
  nucleo-ui-outline-duo-18: ^1.3.2
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.2
  typescript: ^5.9.3
  uuid: ^13.0.0
  vite: ^8.0.0
  wrangler: ^4.75.0
  zod: ^4.3.6
