packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@cloudflare/vite-plugin": ^1.43.0
  "@orpc/client": ^1.14.6
  "@polar-sh/better-auth": ^1.8.4
  "@tailwindcss/vite": ^4.3.2
  "@types/react": ^19.2.17
  "@types/react-dom": ^19.2.3
  astro: ^6.4.8
  better-auth: ^1.6.23
  clsx: ^2.1.1
  nucleo-ui-outline-18: ^1.5.0
  nucleo-ui-outline-duo-18: ^1.5.0
  react: ^19.2.7
  react-dom: ^19.2.7
  tailwind-merge: ^3.6.0
  tailwindcss: ^4.3.2
  uuid: ^14.0.1
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  wrangler: ^4.107.0
  zod: ^4.4.3
  vitest: 4.1.10
  vite-plus: 0.2.4

minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/vite-plus-*"
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"

overrides:
  vite: "catalog:"
  kysely: 0.28.17
  vitest: "catalog:"

allowBuilds:
  better-sqlite3: true
  nucleo-ui-outline-18: true
  nucleo-ui-outline-duo-18: true
  nucleo-core-outline-24: true
  "@cloudflare/vite-plugin": true
  "@google/genai": false
  core-js: false
  esbuild: false
  msgpackr-extract: false
  protobufjs: false
  sharp: false
  workerd: false
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
