/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as ApiContentPublishRouteImport } from './routes/api/content/publish'
import { Route as ApiContentManifestRouteImport } from './routes/api/content/manifest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentPublishRoute = ApiContentPublishRouteImport.update({
  id: '/api/content/publish',
  path: '/api/content/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContentManifestRoute = ApiContentManifestRouteImport.update({
  id: '/api/content/manifest',
  path: '/api/content/manifest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/api/content/manifest': typeof ApiContentManifestRoute
  '/api/content/publish': typeof ApiContentPublishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/api/content/manifest': typeof ApiContentManifestRoute
  '/api/content/publish': typeof ApiContentPublishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$': typeof DocsSplatRoute
  '/api/content/manifest': typeof ApiContentManifestRoute
  '/api/content/publish': typeof ApiContentPublishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs/$' | '/api/content/manifest' | '/api/content/publish'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/$' | '/api/content/manifest' | '/api/content/publish'
  id:
    | '__root__'
    | '/'
    | '/docs/$'
    | '/api/content/manifest'
    | '/api/content/publish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiContentManifestRoute: typeof ApiContentManifestRoute
  ApiContentPublishRoute: typeof ApiContentPublishRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/publish': {
      id: '/api/content/publish'
      path: '/api/content/publish'
      fullPath: '/api/content/publish'
      preLoaderRoute: typeof ApiContentPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/content/manifest': {
      id: '/api/content/manifest'
      path: '/api/content/manifest'
      fullPath: '/api/content/manifest'
      preLoaderRoute: typeof ApiContentManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiContentManifestRoute: ApiContentManifestRoute,
  ApiContentPublishRoute: ApiContentPublishRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
